# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
# Copy package.json and lock files
COPY package.json package-lock.json* pnpm-lock.yaml* ./

# Install only production dependencies initially
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN npm run build

# Expose no ports, use stdio

# Default command to run the MCP server
CMD ["node", "build/index.js"]
